image: rust:latest

stages:
  - build

before_script:
  # Instalacja niezbędnych narzędzi
  - apt-get update && apt-get install -y curl unzip
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - source $HOME/.cargo/env
  - rustup target add aarch64-linux-android
  - rustup target add armv7-linux-androideabi
  - rustup target add i686-linux-android
  - rustup target add x86_64-linux-android
  - cargo install tauri-cli

build:
  stage: build
  script:
    - cd src-tauri
    - cargo tauri build --target aarch64-linux-android
  artifacts:
    paths:
      - src-tauri/target/release/*.apk
